/**
 * featureMeta.js
 * --------------
 * Ground truth for every feature the model uses:
 *   - human-readable label
 *   - type: 'structural' (binary) vs 'statistical' (continuous)
 *   - model importance weight (from RandomForest feature_importances_)
 *   - AI-style explanation for the ScanModal panel
 *
 * Order matches backend/feature_extraction.py FEATURE_NAMES (21 total).
 */

export const FEATURE_META = {
  // ── Structural (binary) ─────────────────────────────────────────────────
  ip: {
    label: 'IP Address as Hostname',
    type: 'structural',
    importance: 0.045,
    explain: 'The URL uses a raw IP address instead of a registered domain name — a classic phishing indicator used to evade domain reputation checks.',
  },
  https_token: {
    label: 'HTTPS Token in URL Path',
    type: 'structural',
    importance: 0.038,
    explain: 'The word "https" appears within the URL path or query string, not just the protocol. Attackers do this to trick users into thinking the link is secure.',
  },
  prefix_suffix: {
    label: 'Prefix / Suffix in Domain',
    type: 'structural',
    importance: 0.042,
    explain: 'The domain contains hyphens used to add fake prefixes or suffixes (e.g. "paypal-secure.com"), mimicking trusted brand names.',
  },
  shortening_service: {
    label: 'URL Shortening Service',
    type: 'structural',
    importance: 0.035,
    explain: 'The URL was generated by a known shortening service (bit.ly, tinyurl, etc.), which hides the true destination from the user.',
  },
  suspicious_tld: {
    label: 'Suspicious TLD',
    type: 'structural',
    importance: 0.052,
    explain: 'The top-level domain (.tk, .ml, .xyz, .work, etc.) is frequently associated with free/cheap domain abuse and phishing campaigns.',
  },
  statistical_report: {
    label: 'Blocklisted IP / Domain',
    type: 'structural',
    importance: 0.041,
    explain: 'The host matches a known malicious IP address or domain from public threat-intelligence blocklists.',
  },

  // ── Statistical (continuous) ────────────────────────────────────────────
  length_url: {
    label: 'URL Length',
    type: 'statistical',
    importance: 0.065,
    explain: 'Phishing URLs are significantly longer on average (mean 74.87) vs legitimate URLs (mean 47.87), as attackers pad them with noise to obscure the real domain.',
  },
  length_hostname: {
    label: 'Hostname Length',
    type: 'statistical',
    importance: 0.048,
    explain: 'Long hostnames are correlated with phishing — attackers concatenate brand names and keywords to produce lengthy subdomains.',
  },
  nb_dots: {
    label: 'Dot Count',
    type: 'statistical',
    importance: 0.044,
    explain: 'Higher dot count (e.g. "paypal.secure.account.update.tk") indicates deeply nested subdomains used to fake legitimate-looking paths.',
  },
  nb_hyphens: {
    label: 'Hyphen Count',
    type: 'statistical',
    importance: 0.038,
    explain: 'Multiple hyphens in the hostname are associated with keyword-stuffed phishing domains (e.g. "secure-login-paypal-account.com").',
  },
  nb_qm: {
    label: 'Query Mark Count',
    type: 'statistical',
    importance: 0.035,
    explain: 'Multiple question marks suggest obfuscated query parameters often used in redirect chains in phishing kits.',
  },
  nb_percent: {
    label: 'Percent-Encoded Characters',
    type: 'statistical',
    importance: 0.032,
    explain: 'URL-encoded characters (%XX) are used to bypass simple string-matching filters and hide malicious keywords.',
  },
  nb_slash: {
    label: 'Slash Count',
    type: 'statistical',
    importance: 0.041,
    explain: 'A higher number of path segments can indicate deep redirect chains or keyword-padded paths used in phishing URLs.',
  },
  nb_www: {
    label: 'WWW Occurrences',
    type: 'statistical',
    importance: 0.028,
    explain: 'Multiple "www" occurrences in a single URL signal attempts to spoof familiar-looking addresses.',
  },
  ratio_digits_url: {
    label: 'Digit Ratio (Full URL)',
    type: 'statistical',
    importance: 0.055,
    explain: 'A high proportion of digits in the URL path suggests obfuscation or randomly generated phishing pages.',
  },
  ratio_digits_host: {
    label: 'Digit Ratio (Hostname)',
    type: 'statistical',
    importance: 0.048,
    explain: 'IP-like or digit-heavy hostnames strongly correlate with phishing infrastructure that avoids registering memorable domains.',
  },
  char_repeat: {
    label: 'Character Repetition Score',
    type: 'statistical',
    importance: 0.042,
    explain: 'Repeated character sequences (e.g. "aaaaaa") indicate randomly generated or obfuscated phishing domains.',
  },
  avg_words_raw: {
    label: 'Avg Word Length (Raw URL)',
    type: 'statistical',
    importance: 0.038,
    explain: 'Unusually long words in the raw URL are produced by concatenating brand names + attack keywords without separators.',
  },
  avg_word_host: {
    label: 'Avg Word Length (Hostname)',
    type: 'statistical',
    importance: 0.041,
    explain: 'Long average word length in the hostname is a strong indicator of keyword-stuffed phishing domains.',
  },
  avg_word_path: {
    label: 'Avg Word Length (Path)',
    type: 'statistical',
    importance: 0.035,
    explain: 'Longer-than-normal path words often represent padded redirect tokens used in phishing kits.',
  },
  phish_hints: {
    label: 'Phishing Keyword Hits',
    type: 'statistical',
    importance: 0.072,
    explain: 'The path contains known phishing-related keywords (login, signin, admin, dropbox, paypal, etc.) — the strongest single statistical predictor.',
  },
}

/** Derive display status from a 0-1 risk score */
export const getStatus = (riskScore) => {
  if (riskScore >= 0.70) return 'Phishing'
  if (riskScore >= 0.40) return 'Suspicious'
  return 'Safe'
}

/** Build the breakdown array used by ScanModal and StatChart */
export const buildBreakdown = (features) => {
  const maxImportance = Math.max(...Object.values(FEATURE_META).map(m => m.importance))
  return Object.entries(features).map(([key, value]) => {
    const meta = FEATURE_META[key] || { label: key, type: 'statistical', importance: 0.03, explain: '' }
    return {
      key,
      value: Number(value),
      label: meta.label,
      type: meta.type,
      importance: meta.importance,
      explain: meta.explain,
      normImportance: meta.importance / maxImportance,
    }
  })
}
