"""
PDF report generator for Deepfake Detective.

Creates a formatted forensic report with scan results,
heatmaps, and analysis details.
"""

from __future__ import annotations

import io
import base64
import numpy as np
import cv2
from fpdf import FPDF
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime


class ForensicReport(FPDF):
    """Custom PDF layout for deepfake forensic reports."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(59, 130, 246)
        self.cell(0, 10, "Deepfake Detective - Forensic Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(30, 58, 95)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10,
                  f"Generated by Deepfake Detective | Page {self.page_no()}/{{nb}} | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                  align="C")


def generate_report(scan_result: Dict,
                    heatmap_frame: Optional[np.ndarray] = None,
                    output_path: Optional[str | Path] = None) -> bytes:
    """
    Generate a PDF forensic report from scan results.

    Args:
        scan_result:   Full analysis result dict from the backend.
        heatmap_frame: Optional BGR frame with Grad-CAM overlay.
        output_path:   Optional file path to save the PDF.

    Returns:
        PDF file contents as bytes.
    """
    pdf = ForensicReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Summary Section ─────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(226, 232, 240)
    pdf.cell(0, 8, "Scan Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(148, 163, 184)

    scan_id = scan_result.get("id", "N/A")
    timestamp = scan_result.get("timestamp", datetime.now().isoformat())
    filename = scan_result.get("filename", "Unknown")
    verdict = scan_result.get("verdict", "Unknown")
    final_score = scan_result.get("final_score", 0)
    confidence = scan_result.get("confidence", "N/A")

    summary_rows = [
        ("Scan ID", scan_id),
        ("Timestamp", timestamp),
        ("File", filename),
        ("Verdict", verdict),
        ("Risk Score", f"{round(final_score * 100)}%"),
        ("Confidence", confidence),
    ]

    for label, value in summary_rows:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, f"{label}:", new_x="RIGHT")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # ── Score Breakdown ─────────────────────────────────────────────
    video_result = scan_result.get("video_analysis") or {}
    audio_result = scan_result.get("audio_analysis") or {}

    if video_result or audio_result:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(226, 232, 240)
        pdf.cell(0, 8, "Score Breakdown", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(148, 163, 184)

        if video_result:
            v_score = video_result.get("mean_score", video_result.get("score", 0))
            v_std = video_result.get("std_score", 0)
            pdf.cell(0, 7,
                     f"Video Score: {round(v_score * 100)}% +/- {round(v_std * 100)}%",
                     new_x="LMARGIN", new_y="NEXT")

        if audio_result:
            a_score = audio_result.get("combined_score", audio_result.get("score", 0))
            a_std = audio_result.get("std_score", 0)
            pdf.cell(0, 7,
                     f"Audio Score: {round(a_score * 100)}% +/- {round(a_std * 100)}%",
                     new_x="LMARGIN", new_y="NEXT")

        pdf.ln(5)

    # ── Heatmap Image ───────────────────────────────────────────────
    if heatmap_frame is not None:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(226, 232, 240)
        pdf.cell(0, 8, "Grad-CAM Heatmap (Most Suspicious Frame)",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Encode frame to temp PNG
        success, buf = cv2.imencode(".png", heatmap_frame)
        if success:
            img_io = io.BytesIO(buf.tobytes())
            pdf.image(img_io, x=30, w=150)
            pdf.ln(5)

    # ── Audio Anomalies ─────────────────────────────────────────────
    anomalies = audio_result.get("anomalies", {})
    if anomalies:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(226, 232, 240)
        pdf.cell(0, 8, "Audio Forensic Analysis",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for key, info in anomalies.items():
            detected = info.get("detected", False)
            severity = info.get("severity", "Low") if detected else "OK"
            explanation = info.get("explanation", "")

            icon = "[!]" if detected else "[OK]"

            pdf.set_font("Helvetica", "B", 10)
            color = (239, 68, 68) if severity == "High" else \
                    (245, 158, 11) if severity == "Medium" else (16, 185, 129)
            pdf.set_text_color(*color)
            pdf.cell(8, 6, icon, new_x="RIGHT")

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(226, 232, 240)
            pdf.cell(50, 6, key.replace("_", " ").title(), new_x="RIGHT")

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(148, 163, 184)
            pdf.multi_cell(0, 5, explanation)
            pdf.ln(2)

    # ── Explanation Section ──────────────────────────────────────────
    explanations = scan_result.get("explanations", [])
    if explanations:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(226, 232, 240)
        pdf.cell(0, 8, "Detection Explanations",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(148, 163, 184)
        for exp in explanations:
            pdf.multi_cell(0, 5, f"- {exp}")
            pdf.ln(1)

    # ── Output ──────────────────────────────────────────────────────
    pdf_bytes = pdf.output()

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)

    return pdf_bytes


def frame_to_base64(frame_bgr: np.ndarray, fmt: str = ".png") -> str:
    """Encode a BGR frame to base64 string for API response."""
    success, buf = cv2.imencode(fmt, frame_bgr)
    if not success:
        return ""
    return base64.b64encode(buf.tobytes()).decode("utf-8")
